site_name: 'Siva Sankar Rajendran'
site_description: 'My Online Identity'
site_author: 'Siva Sankar Rajendran'
site_favicon: 'img/favicon.ico'
site_url: 'http://sivasankar-r.github.io'

# Theme
theme: material

# Options
extra:
  logo: 'img/sivapcu.png'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  disqus: 'sivasankar-r-github-io'
  social:
    - type: 'github'
      link: 'https://github.com/sivasankar-r'
    - type: 'twitter'
      link: 'https://twitter.com/sivapcu'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/siva-sankar-rajendran'

# Google Analytics
google_analytics:
  - 'UA-99603126-1'
  - 'auto'

# Extensions
markdown_extensions:
  - pymdownx.tasklist
  - pymdownx.superfences
  - admonition
  - codehilite(linenums=true)
  - toc(permalink=true)
  - attr_list

# Pages
pages:
  - Home: 'index.md'
  - Notes:
    - Online Tools: 'blog/online-tools.md'
    - VS Code Tips: 'blog/vscode-tips.md'
    - MkDocs Notes: 'blog/mkdocs-notes.md'
  - Computer Science:
    - Data Structures:
      - Introduction: 'computer-science/data-structures/introduction.md'
      - Boundary Conditions: 'computer-science/data-structures/boundary-conditions.md'
      - Arrays: 'computer-science/data-structures/arrays.md'
      - Linked List: 'computer-science/data-structures/linked-list.md'
      - Stack: 'computer-science/data-structures/stack.md'
      - Queue: 'computer-science/data-structures/queue.md'
      - Tree: 'computer-science/data-structures/tree.md'
      - Graph: 'computer-science/data-structures/graph.md'
    - Algorithms:
      - Sorting:
        - Bubble Sort: 'computer-science/algorithms/sorting/bubble-sort.md'
        - Insertion Sort: 'computer-science/algorithms/sorting/insertion-sort.md'
        - Quick Sort: 'computer-science/algorithms/sorting/quick-sort.md'
    - Design Patterns:
      - Strategy Pattern: 'computer-science/design-patterns/strategy-pattern.md'
      - Observer Pattern: 'computer-science/design-patterns/observer-pattern.md'
  - Personal:
    - Running: 'running/running.md'