site_name: 'Siva Sankar Rajendran'
site_description: 'My Online Identity'
site_author: 'sivapcu'
site_favicon: 'img/favicon.ico'
site_url: 'http://sivapcu.github.io'

# Theme
theme: material

# Options
extra:
  logo: 'img/sivapcu.png'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  disqus: 'sivapcu-github-io'
  social:
    - type: 'github'
      link: 'https://github.com/sivapcu'
    - type: 'twitter'
      link: 'https://twitter.com/sivapcu'
    - type: 'linkedin'
      link: 'https://linkedin.com/'

# Google Analytics
google_analytics:
  - 'UA-99603126-1'
  - 'auto'

# Extensions
markdown_extensions:
  - pymdownx.tasklist
  - pymdownx.superfences
  - admonition
  - codehilite(linenums=true)
  - toc(permalink=true)
  - attr_list

# Pages
pages:
  - Home: 'index.md'
  - Notes:
    - Data Structures:
      - Boundary Conditions: 'notes/data-structures/boundary-conditions.md'
      - Linked List: 'notes/data-structures/linked-list.md'
    - Algorithms:
      - Sorting:
        - Bubble Sort: 'notes/algorithms/sorting/bubble-sort.md'
    - Design Patterns:
      - Strategy Pattern: 'notes/design-patterns/strategy-pattern.md'
      - Observer Pattern: 'notes/design-patterns/observer-pattern.md'
  - Bookmarks:
    - Online Tools: 'bookmarks/online-tools.md'